spring:
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/bioinfo
  http:
    encoding:
      charset=UTF-8:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bioinfo?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  mail:                             #邮箱配置
    host: smtp.163.com              #使用163邮箱服务器
    username: XXXX@163.com   #你的163邮箱
    password: XXXXXXXX      #SMTP授权密码 (不是密码)
    port: 25
    protocol: smtp
    default-encoding: UTF-8
    jndi-name: email

jwt:
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
bioinfo:
    workDir: ${user.home}/.bioinfo

#https://www.jianshu.com/p/35878d4ec130
server:
  tomcat:
    max-threads: 200
    max-connections: 300
  port: 8080
https:
  ssl:
    key-store: classpath:sample.pfx #配置证书路径
    key-store-password: 3bWBoh69 #证书密码
  port: 8081


